version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
